"""Composite provider implementing the fallback strategy.

Tries each provider in the configured order and returns the first answer. Failures
are collected as ``notes`` so the UI (and the API consumer) can see why the chain
degraded instead of guessing.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import replace

from tv_insight.application.errors import ProviderUnavailable
from tv_insight.application.ports.insight import (
    InsightProvider,
    InsightRequest,
    InsightResult,
)
from tv_insight.infrastructure.logging import get_logger

logger = get_logger(__name__)


class FallbackInsightProvider(InsightProvider):
    """Ordered chain of providers.

    A provider boundary is exactly the right place to catch broadly: one vendor's
    unexpected exception must not take down the feature when a healthy provider
    sits behind it. Every swallowed exception is logged and surfaced as a note.
    """

    def __init__(self, providers: Sequence[InsightProvider]) -> None:
        if not providers:
            raise ValueError("FallbackInsightProvider needs at least one provider")
        self._providers = tuple(providers)

    @property
    def name(self) -> str:
        return f"fallback[{'+'.join(provider.name for provider in self._providers)}]"

    def is_available(self) -> bool:
        return any(provider.is_available() for provider in self._providers)

    @property
    def providers(self) -> tuple[InsightProvider, ...]:
        return self._providers

    async def generate(
        self, request: InsightRequest, *, refresh: bool = False
    ) -> InsightResult:
        notes: list[str] = []

        for provider in self._providers:
            if not provider.is_available():
                notes.append(f"{provider.name}: skipped, not configured")
                continue

            try:
                result = await provider.generate(request, refresh=refresh)
            except Exception as exc:  # noqa: BLE001 - deliberate bulkhead
                logger.warning("insight provider %s failed: %s", provider.name, exc)
                notes.append(f"{provider.name}: {exc}")
                continue

            logger.info("insight generated by provider=%s", result.provider)
            if notes:
                return replace(result, notes=result.notes + tuple(notes))
            return result

        raise ProviderUnavailable("Every insight provider failed: " + "; ".join(notes))
