"""initial schema: comments and watched_episodes

Revision ID: 0001_initial
Revises:
Create Date: 2024-01-01 00:00:00

Hand written rather than autogenerated so the first migration is reviewable and
does not depend on a live database being present when the repository is cloned.
``alembic check`` in CI verifies it still matches the models.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("viewer_id", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=16), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_comments_viewer_id", "comments", ["viewer_id"])
    op.create_index("ix_comments_series_id", "comments", ["series_id"])
    op.create_index("ix_comments_episode_id", "comments", ["episode_id"])
    op.create_index("ix_comments_created_at", "comments", ["created_at"])
    op.create_index(
        "ix_comments_series_target_created",
        "comments",
        ["series_id", "target", "created_at"],
    )
    op.create_index(
        "ix_comments_episode_created", "comments", ["episode_id", "created_at"]
    )

    op.create_table(
        "watched_episodes",
        sa.Column("viewer_id", sa.String(length=64), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("watched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("viewer_id", "episode_id"),
    )
    op.create_index(
        "ix_watched_episodes_series_id", "watched_episodes", ["series_id"]
    )
    op.create_index(
        "ix_watched_viewer_series", "watched_episodes", ["viewer_id", "series_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_watched_viewer_series", table_name="watched_episodes")
    op.drop_index("ix_watched_episodes_series_id", table_name="watched_episodes")
    op.drop_table("watched_episodes")

    op.drop_index("ix_comments_episode_created", table_name="comments")
    op.drop_index("ix_comments_series_target_created", table_name="comments")
    op.drop_index("ix_comments_created_at", table_name="comments")
    op.drop_index("ix_comments_episode_id", table_name="comments")
    op.drop_index("ix_comments_series_id", table_name="comments")
    op.drop_index("ix_comments_viewer_id", table_name="comments")
    op.drop_table("comments")
